# -- Kubernetes DNS Domain name to use
clusterDomain: cluster.local

# SMI Adaptor configuration
adaptor:
  image:
    # -- Docker registry for the adaptor instance
    registry: cr.l5d.io/linkerd
    # -- Docker image name for the adaptor instance
    name: smi-adaptor
    # -- Docker image tag for the adaptor instance
    tag: linkerdSMIVersionValue
    # -- Pull policy  for the adaptor instance
    pullPolicy: IfNotPresent

  # -- Affinity for the adaptor instance
  affinity: {}
  # -- Node selector for the adaptor instance
  nodeSelector: {}
  # -- Tolerations for the adaptor instance
  tolerations: []
