# -- Set to false when installing in a custom namespace
installNamespace: true

# -- Namespace in which to install the SMI extension
namespace: linkerd-smi

# -- Kubernetes DNS Domain name to use
clusterDomain: cluster.local

# SMI Adaptor configuration
adaptor:
  image:
    # -- Docker registry for the adaptor instance
    registry: ghcr.io/linkerd
    # -- Docker image name for the adaptor instance
    name: smi-adaptor
    # -- Docker image tag for the adaptor instance
    tag: linkerdSMIVersionValue
    # -- Pull policy  for the adaptor instance
    pullPolicy: IfNotPresent
